cradox is not supported anymore.
gnocchixyz/gnocchi pull request #1068
Opened 2020-09-07 06:37 UTC by mrunge

Update the docs etc. to use rados directly.

2020-09-07 08:29 UTC, jd approved these changes

2020-09-08 15:18 UTC, chungg approved these changes
will force merge this later.

2020-09-10 11:48 UTC, mrunge commented
Thank you.

2020-09-15 15:55 UTC, tobias-urdin commented
lets merge this now t hat CI is passing

2020-09-15 18:15 UTC, chungg commented
@Mergifyio rebase

2020-09-17 12:32 UTC, chungg commented
i tried this using latest image and it could be an issue with cradox and whatever ceph version comes with Bionic. i got:
```
{0} gnocchi.tests.test_indexer.TestIndexerDriver.test_delete_resource [60.964418s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/__init__.py", line 117, in NUM_SACKS'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/ceph.py", line 70, in _get_storage_sacks'
    b'  File "cradox.pyx", line 499, in cradox.requires.wrapper.validate_func'
    b'  File "cradox.pyx", line 2695, in cradox.Ioctx.read'
    b"cradox.TimedOut: [errno 110] Ioctx.read(b'`\\xb4e\\xd2\\xee\\x7f'): failed to read b'gnocchi-config'"
    b''
    b'During handling of the above exception, another exception occurred:'
    b''
    b'Traceback (most recent call last):'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/__init__.py", line 127, in upgrade'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/__init__.py", line 119, in NUM_SACKS'
    b"gnocchi.incoming.SackDetectionError: [errno 110] Ioctx.read(b'`\\xb4e\\xd2\\xee\\x7f'): failed to read b'gnocchi-config'"
    b''
    b'During handling of the above exception, another exception occurred:'
    b''
    b'Traceback (most recent call last):'
    b'  File "/home/tester/gnocchi/gnocchi/tests/base.py", line 60, in skip_if_not_implemented'
    b'  File "/home/tester/gnocchi/gnocchi/tests/base.py", line 373, in setUp'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/__init__.py", line 129, in upgrade'
    b'  File "/home/tester/gnocchi/gnocchi/incoming/ceph.py", line 74, in set_storage_settings'
    b'  File "cradox.pyx", line 499, in cradox.requires.wrapper.validate_func'
    b'  File "cradox.pyx", line 2626, in cradox.Ioctx.write_full'
    b"cradox.TimedOut: [errno 110] Ioctx.write_full(b'\\x01'): failed to write b'gnocchi-config'"
    b''
```

don't know how to make tox use libraries not from pypi but i think we need to use python3-rados

2020-09-17 12:51 UTC, mrunge commented
cradox is not supported, see https://github.com/sileht/pycradox

Unfortunately, I haven't found a rados package in pypi, there are distribution packages though, like the before mentioned python3-rados

2020-09-29 16:10 UTC, mrunge commented
Is there anything I can do to help getting this merged?

2020-09-29 16:38 UTC, jd commented
Looks like travis did not run. :(

2020-09-29 16:49 UTC, jd commented
Anyone knows why Travis is lazy on this one?

2020-09-30 10:16 UTC, tobias-urdin requested changes
Let's hold off with this until the CI fix for Bionic is merged as well then rebase this.

2020-09-30 10:16 UTC, tobias-urdin commented on .travis.yml
> +    sudo apt install -y python3-rados
This doesn't have any effect, please remove this. The package is maintained inside the Docker container used for testing.

2020-10-01 20:30 UTC, merged