Remove Docker
gnocchixyz/gnocchi pull request #1087
Opened 2020-12-03 15:40 UTC by tobias-urdin

Run testing directly on the Ubuntu node to simply
the logic and make it easier to test and see output.

2020-12-03 16:02 UTC, jd commented
That's going to increase the CI runtime quite a bit though :(

2020-12-03 16:05 UTC, tobias-urdin commented
Yeah :( just testing though for now

2020-12-03 21:11 UTC, tobias-urdin commented
It's even worse waiting 5+ hours for Travis CI to run the tests since there is 6.5k open source jobs in queue :p

2020-12-07 08:38 UTC, tobias-urdin commented
@mergifyio rebase

2020-12-11 10:24 UTC, mrunge requested changes

2020-12-11 10:24 UTC, mrunge commented on .travis.yml
> +  - ulimit -a
missing a sudo?

2020-12-11 10:24 UTC, mrunge commented on .travis.yml
> +  - ulimit -n 50000
then same here

2020-12-11 11:16 UTC, tobias-urdin commented on .travis.yml
> +  - ulimit -a
nope has nothing to do with it

2020-12-11 11:17 UTC, tobias-urdin commented on .travis.yml
> +  - ulimit -a
the limit is enforced by travis-ci

2021-07-02 09:42 UTC, tobias-urdin commented
will be handled another way

2021-07-02 09:42 UTC, closed without merging