Fix yaml deprecation warning
gnocchixyz/gnocchi pull request #1099
Opened 2020-12-11 08:00 UTC by mrunge

YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,
as the default Loader is unsafe. Please read https://msg.pyyaml.org/load
for full details.

2020-12-11 09:15 UTC, jd approved these changes

2020-12-11 09:16 UTC, jd requested changes

2020-12-11 09:16 UTC, jd commented on gnocchi/gendoc.py
> +        scenarios = ScenarioList(yaml.load(f), Loader=yaml.FullLoader)
syntax error I think

2020-12-11 09:22 UTC, mrunge commented on gnocchi/gendoc.py
> +        scenarios = ScenarioList(yaml.load(f), Loader=yaml.FullLoader)
embarrassing. Yes, of course!

2020-12-11 09:54 UTC, jd approved these changes

2020-12-11 09:55 UTC, mrunge commented
Thank you for looking at this Julien!

2020-12-11 10:02 UTC, mrunge commented
https://github.com/gnocchixyz/gnocchi/pull/1097 also contains a commit to pin chardet<4, which seems to be necessary here as well? Let's see if the other patch passes.

2020-12-14 15:05 UTC, mrunge commented
It seems pinning chardet is necessary here for the time being.

@jd may I ask for a review again?

2020-12-14 15:50 UTC, jd commented
@mergifyio refresh

2020-12-14 15:51 UTC, merged

2020-12-14 15:55 UTC, mrunge commented
Thank you.

2020-12-16 14:22 UTC, tobias-urdin commented
@mergifyio backport-to-4.3

2020-12-16 14:29 UTC, tobias-urdin commented
@Mergifyio backport stable/4.3