Limit maximum metrics to be deleted simultaniously
gnocchixyz/gnocchi pull request #1125
Opened 2021-03-18 14:17 UTC by felixhuettner

Currently gnocchi-metricd tries to collect all metrics that should be deleted
and deletes them in one big loop. If a large amount of old metrics has
accumulated this will cause high load on the database as it needs to find
and sort all of these rows. It will also cause a high amount of memory usage
for gnocchi-metricd as it needs to also sort all of these rows in memory.

To fix this the amount of rows being deleted in one run is limited to 10000.
This is sufficient to allow gnocchi to cleanup metrics in a fast way under
normal circumstances while still allowing it to catch up if no deletion has
been performed for a while.

Signed-off-by: Felix Huettner <felix.huettner@mail.schwarz>

2021-03-18 14:37 UTC, felixhuettner commented
Hi everyone,
i'm not sure about the CI Runs but the issues do not seem to be related to the PR in any way

2021-03-18 14:53 UTC, jd submitted a review, later dismissed
Can we make this configurable?

2021-03-18 15:14 UTC, felixhuettner commented
Implemented a configuration option. Not sure about the name though

2021-03-18 15:33 UTC, jd submitted a review, later dismissed

2021-03-18 15:33 UTC, jd commented on gnocchi/opts.py
> +                       "simultaniously by one janitor."),
```suggestion
                       "simultaneously by one janitor."),
```

2021-03-18 15:33 UTC, jd commented on gnocchi/opts.py
> +            cfg.IntOpt('janitor_batch_size',
```suggestion
            cfg.IntOpt('cleanup_batch_size',
```
there's `metric_cleanup_delay` already

2021-03-18 15:39 UTC, felixhuettner commented on gnocchi/opts.py
> +            cfg.IntOpt('janitor_batch_size',
fixed

2021-03-18 15:39 UTC, felixhuettner commented on gnocchi/opts.py
> +                       "simultaniously by one janitor."),
fixed

2021-03-18 15:54 UTC, jd reviewed
Thank you!
IIRC the doc is autogenerated. Maybe adding a release note with `reno` would be cool? :)

2021-03-19 07:45 UTC, felixhuettner commented
I hope i got the release note format correctly :)

2021-03-19 14:02 UTC, jd approved these changes
Yeah this is great! Thank you!

2021-03-19 14:02 UTC, jd commented on releasenotes/notes/configurable_clenaup_batch_size-a785c1aa6ee29058.yaml
> +    Out-of-memory errors.
```suggestion
    out-of-memory errors.
```

2021-03-19 14:02 UTC, jd commented
The CI seems broken of the latest tenacity, somebody should rewrite the current code to stop using the deprecated now-removed API.

2021-03-22 10:36 UTC, felixhuettner commented
What is then the best way to go forward here? Should we just leave it sitting here until the CI is fixed (that would be fine with me)

2021-03-22 11:25 UTC, jd requested changes
Yes, feel free to give a hand to fix the CI. Not sure anybody is working on it 😢

2021-03-22 12:45 UTC, felixhuettner commented
Would you have any details where i could start taking a look? Then i'll see if i can get some time for that

2021-03-22 13:19 UTC, jd commented
The latest tenacity release https://pypi.org/project/tenacity/ 7.0.0 removed old compat code for retry functions.
It seems Gnocchi is providing its own retry function and they need to be rewritten for the new API. That should not be hard.

2021-03-25 10:52 UTC, mrunge commented
I've put together a PR to fix CI by pinning tenacity and sqlalchemy, https://github.com/gnocchixyz/gnocchi/pull/1124
There is also a bump for oslo.policy included. This patch currently fails in upgrade tests; I've also submitted the same for the previous branch, (which fails in ubgrade checks from 4.2...)

2021-03-26 13:02 UTC, tobias-urdin commented
@Mergifyio rebase

2021-03-26 13:19 UTC, jd approved these changes

2021-03-26 13:20 UTC, jd commented
@mergifyio update

2021-03-29 11:31 UTC, felixhuettner commented
:D ok that is fixed now.
Let me try this
@Mergifyio update

2021-03-29 11:37 UTC, felixhuettner commented
:D ok, let's do it manually

2021-03-29 12:34 UTC, jd approved these changes

2021-07-07 21:30 UTC, tobias-urdin commented
@Mergifyio rebase

2021-07-11 17:52 UTC, merged