Enable the update of archive policy back window
gnocchixyz/gnocchi pull request #1278
Opened 2022-12-26 14:32 UTC by rafaelweingartner

2022-12-26 16:56 UTC, rafaelweingartner commented
Errors are not related to the PR

2022-12-30 11:44 UTC, rafaelweingartner commented
This PR depends on the merge of https://github.com/gnocchixyz/gnocchi/pull/1279

2023-01-20 00:28 UTC, tobias-urdin commented
@mergifyio rebase

2023-01-20 11:04 UTC, tobias-urdin requested changes
I would be OK merging this in master but it need to update some testing and documentation as well. Also added a two comments that would be good to adress to prevent possible KeyError's.

2023-01-20 11:04 UTC, tobias-urdin commented on gnocchi/indexer/sqlalchemy.py
> +            if kwargs.get("back_window") is not None:
kwargs.get("back_window", None)

2023-01-20 11:04 UTC, tobias-urdin commented on gnocchi/rest/api.py
> +                back_window=body.get('back_window'))
Same here maybe?
body.get('back_window', None)

2023-01-20 13:48 UTC, rafaelweingartner commented on gnocchi/rest/api.py
> +                back_window=body.get('back_window'))
Same here

2023-01-20 16:31 UTC, tobias-urdin commented on gnocchi/indexer/sqlalchemy.py
> +            if kwargs.get("back_window") is not None:
Ok, good 👍

2023-01-20 16:35 UTC, rafaelweingartner commented
@tobias-urdin thanks for the review. I added tests and documentation as you requested.

2023-01-22 16:33 UTC, tobias-urdin approved these changes

2023-01-22 16:49 UTC, merged