Drop use of build_sphinx distutils command
gnocchixyz/gnocchi pull request #1325
Opened 2023-08-03 11:12 UTC by stephenfin

Drop use of the `build_sphinx` distutils command, which was dropped in Sphinx 7.x. distutils itself is deprecated and will be removed in Python 3.12.

While we're here, we also fix up some other issues with tox and the setup files in general. The commit messages hold more information about this.

2023-08-03 14:20 UTC, stephenfin commented
Depends on #1329.

2023-09-05 10:03 UTC, tobias-urdin commented
@stephenfin thanks, this all looks good to me except for removal of `docs-gnocchi-web` tox env. I think that's used somehow to roll out https://gnocchi.osci.io but I don't have access to that so I'm not sure. It's also building that but ignoring warnings to not fail I guess(?).

Can we leave that in and fix the conflict and I'll pull this in asap to unblock sphinx7, thanks!

2023-09-05 12:47 UTC, stephenfin commented
> @stephenfin thanks, this all looks good to me except for removal of `docs-gnocchi-web` tox env. I think that's used somehow to roll out [gnocchi.osci.io](https://gnocchi.osci.io) but I don't have access to that so I'm not sure. It's also building that but ignoring warnings to not fail I guess(?).
> 
> Can we leave that in and fix the conflict and I'll pull this in asap to unblock sphinx7, thanks!

Done. I think the failure is unrelated but I can't rerun it to check.

2023-09-06 07:43 UTC, tobias-urdin requested changes

2023-09-06 07:43 UTC, tobias-urdin commented on .github/workflows/gnocchi.yml
> -          - docs-gnocchi-web
Please also add back this

2023-09-06 07:43 UTC, tobias-urdin commented on .mergify.yml
> -    - check-success=doc (docs-gnocchi-web)
And these two

2023-09-06 11:22 UTC, tobias-urdin commented
Figured out it's handled from here: https://gitlab.com/osci/community-cage-infra-ansible/-/blob/master/roles/gnocchi_builder/templates/gnocchi_builder

2023-09-06 11:33 UTC, stephenfin commented on .mergify.yml
> -    - check-success=doc (docs-gnocchi-web)
Done

2023-09-06 11:33 UTC, stephenfin commented on .github/workflows/gnocchi.yml
> -          - docs-gnocchi-web
Done

2023-09-06 12:53 UTC, tobias-urdin commented
Sorry for all the resistance @stephenfin – please rebase after revert https://github.com/gnocchixyz/gnocchi/pull/1343

2023-09-22 13:19 UTC, stephenfin commented
@tobias-urdin Anything else needed here or can we merge this (I'd like to get it off my TODO list :smile:)

2023-09-25 06:41 UTC, tobias-urdin commented
@stephenfin Thanks!

2023-09-25 06:41 UTC, merged